default_stages: ['commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: debug-statements
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: requirements-txt-fixer

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  - id: add-trailing-comma
    args: [--py36-plus]

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py311-plus]

- repo: https://github.com/bwhmather/ssort
  rev: v0.12.0
  hooks:
  - id: ssort

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--py39-plus]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.15
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/PyCQA/flake8
  rev: 6.1.0
  hooks:
  - id: flake8

- repo: https://github.com/yunojuno/pre-commit-xenon
  rev: v0.1
  hooks:
  - id: xenon
    args: ["--max-average=A", "--max-modules=C", "--max-absolute=C", "."]

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.6
  hooks:
  - id: bandit
    args: [-ll]
    exclude: ^tests/

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.13.0
  hooks:
    - id: commitizen
