name: quality-gate
on:
  push:
    branches:
    - develop
    - main
    - release
    tags:
    - "v*"
  pull_request:
    branches:
    - develop
    - main
    - release

jobs:
  code-quality:
    uses: cdubos-fr/reusable-workflows/.github/workflows/python-ci.yml@v0.1
    with:
      python-version: "3.10"
